### ISSUE TITLE
Does this support RIF rules?

### ISSUE THREAD

**Issue by awxiaoxian2020** [plastovicka/Piskvork#1]
I need a program that supports [RIF rule](https://en.wikipedia.org/wiki/RIF_opening_rule).

**Comment by plastovicka** [comment]
No, it does not support any swap rules.

**Comment by awxiaoxian2020** [comment]
> No, it does not support any swap rules.

Thanks for your reply.

**Comment by awxiaoxian2020** [comment]
Hi @plastovicka 
if I want to impl some swap rules base on it, what file should I modify? and is PR welcome?

**Comment by plastovicka** [comment]
The most difficult task is to modify AI so that it would be able to make proposals and swap sides. Are you going to create your own AI ? Or do you want to modify my AI ? I made it in 2006 and don't remember how it works. 
First of all it would be necessary to update the [protocol](https://plastovicka.github.io/protocl2en.htm). It is implemented in files protocol.cpp and skelet_CPP/pisqpipe.cpp, skelet_CS/PisqPipe.cs, skelet_Delphi/pisqpipe.pas, skelet_Java/GomokuInterface.java, skelet_Python/pisqpipe.py.

**Comment by awxiaoxian2020** [comment]
I will look into it and close this issue temporarily.

**Comment by garry-ut99** [comment]
Try one of these GUIS : 
--------------------------- https://github.com/accreator/Yixin-Board : ------------- OR -------------- https://github.com/Joker2770/qpiskvork : ----------
(more active fork) --------- https://github.com/dhbloo/Yixin-Board :
(compiled binary) --------- https://github.com/dhbloo/rapfi :
![YixinBoardGUI](https://github.com/plastovicka/Piskvork/assets/72945564/19153fe6-5632-4bc8-81da-ec1d8be0a4ed) ![QPiskvork](https://github.com/plastovicka/Piskvork/assets/72945564/70db46bf-2255-49f3-b322-48e32c41e680)

OR : https://github.com/gomoku/RenLib

![RenLib](https://github.com/plastovicka/Piskvork/assets/72945564/55031d24-5292-4a64-8c43-2e55b5651ec1)



However, apart of supporting more rules, be aware that they miss many features of Piskvork (tournaments, network tournaments/games, QPiskvork also misses logging).
